#!/usr/bin/env python3
"""Add the English/Thai UI strings introduced by Strength Training and Coach v2."""

from __future__ import annotations

import json
from pathlib import Path

CATALOG = Path(__file__).parents[1] / "Strand" / "Resources" / "Localizable.xcstrings"
FALLBACK_LOCALES = ("de", "es", "fr", "it", "pt-PT", "ru", "zh-Hans", "zh-Hant")
ENGLISH = {
    "strength.intensity.light": "Light",
    "strength.intensity.moderate": "Moderate",
    "strength.intensity.hard": "Hard",
    "strength.intensity.veryHard": "Very Hard",
}

THAI = {
    "%@, %lld items, %@": "%@, %lld รายการ, %@",
    "Add exercise": "เพิ่มท่า",
    "Add missing exercise": "เพิ่มท่าที่ตกหล่น",
    "Add set": "เพิ่มเซต",
    "All equipment": "อุปกรณ์ทั้งหมด",
    "All muscles": "กล้ามเนื้อทั้งหมด",
    "Body region": "ส่วนของร่างกาย",
    "Complete set": "ทำเซตเสร็จ",
    "Copy previous set": "คัดลอกเซตก่อนหน้า",
    "Create from current workout": "สร้างจากการฝึกครั้งนี้",
    "Delete set": "ลบเซต",
    "Duplicate exercise": "ทำสำเนาท่า",
    "Edit strength workout": "แก้ไขการฝึกเวท",
    "Estimated load": "ภาระโดยประมาณ",
    "Estimated muscular load": "ภาระกล้ามเนื้อโดยประมาณ",
    "Estimated from logged training. Colors are not direct measurements of muscle activation, damage, inflammation, or injury risk.": "ประเมินจากการฝึกที่บันทึกไว้ สีไม่ใช่การวัดการทำงาน ความเสียหาย การอักเสบ หรือความเสี่ยงบาดเจ็บของกล้ามเนื้อโดยตรง",
    "Exercise actions": "ตัวเลือกของท่า",
    "Exercise and set log": "บันทึกท่าและเซต",
    "Favorite exercise": "ท่าโปรด",
    "High": "สูง",
    "Intensity": "ระดับความหนัก",
    "Keep the detected heart-rate workout and add either a complete exercise log or a faster estimated muscle summary.": "เก็บข้อมูลการออกกำลังกายที่ตรวจจับจากอัตราการเต้นหัวใจไว้ แล้วเพิ่มรายละเอียดท่าครบถ้วนหรือสรุปภาระกล้ามเนื้อแบบรวดเร็ว",
    "Light": "หลับตื้น",
    "strength.intensity.light": "เบา",
    "strength.intensity.moderate": "ปานกลาง",
    "strength.intensity.hard": "หนัก",
    "strength.intensity.veryHard": "หนักมาก",
    "Loading offline exercise library…": "กำลังโหลดคลังท่าออฟไลน์…",
    "Loading strength workout…": "กำลังโหลดการฝึกเวท…",
    "Low": "ต่ำ",
    "Main contributing exercises": "ท่าที่ส่งผลหลัก",
    "Mark set incomplete": "ทำเครื่องหมายว่าเซตยังไม่เสร็จ",
    "Moderate": "ปานกลาง",
    "Move down": "เลื่อนลง",
    "Move up": "เลื่อนขึ้น",
    "MUSCLE MAP": "แผนที่กล้ามเนื้อ",
    "Muscle details": "รายละเอียดกล้ามเนื้อ",
    "Muscle map range": "ช่วงข้อมูลแผนที่กล้ามเนื้อ",
    "No strength workouts yet": "ยังไม่มีประวัติการฝึกเวท",
    "No templates yet.": "ยังไม่มีเทมเพลต",
    "Open strength training history": "เปิดประวัติการฝึกเวท",
    "Quick muscle and intensity summary": "สรุปกล้ามเนื้อและความหนักแบบรวดเร็ว",
    "Quick summaries have medium confidence. They do not invent exercises, sets, side-to-side asymmetry, or measured muscle activation.": "สรุปแบบรวดเร็วมีความเชื่อมั่นระดับปานกลาง ระบบจะไม่เดาท่า จำนวนเซต ความแตกต่างซ้าย–ขวา หรือการทำงานของกล้ามเนื้อ",
    "Remove exercise": "นำท่าออก",
    "Residual": "ภาระคงค้าง",
    "Rest complete": "พักครบแล้ว",
    "RPE optional": "RPE (ไม่บังคับ)",
    "Save quick summary": "บันทึกสรุปแบบรวดเร็ว",
    "Save template": "บันทึกเทมเพลต",
    "Saved templates": "เทมเพลตที่บันทึกไว้",
    "Session notes": "บันทึกการฝึก",
    "Session notes (optional)": "บันทึกการฝึก (ไม่บังคับ)",
    "Session RPE": "RPE ของการฝึก",
    "Session RPE (optional)": "RPE ของการฝึก (ไม่บังคับ)",
    "Skip strength details": "ข้ามรายละเอียดการฝึกเวท",
    "Start Strength Training to log exercises, sets, reps, and load.": "เริ่มการฝึกเวทเพื่อบันทึกท่า เซต จำนวนครั้ง และภาระการฝึก",
    "STRENGTH DETAILS": "รายละเอียดการฝึกเวท",
    "STRENGTH TRAINING": "การฝึกเวท",
    "Strength history": "ประวัติการฝึกเวท",
    "Strength Training": "การฝึกเวท",
    "This is a conservative estimate based on logged training and recovery data. It is not a direct measurement and is not medical advice.": "เป็นการประเมินแบบระมัดระวังจากการฝึกและข้อมูลการฟื้นตัวที่บันทึกไว้ ไม่ใช่การวัดโดยตรงหรือคำแนะนำทางการแพทย์",
    "Today": "วันนี้",
    "Today's estimated load": "ภาระโดยประมาณวันนี้",
    "Update": "อัปเดต",
    "Use": "ใช้",
    "Very Hard": "หนักมาก",
    "Very high": "สูงมาก",
    "Workout templates": "เทมเพลตการฝึก",
    "7 days": "7 วัน",
    "7-day estimated load": "ภาระโดยประมาณใน 7 วัน",
    "Estimated residual load": "ภาระคงค้างโดยประมาณ",
    "Working sets today": "เซตหลักวันนี้",
    "Last trained": "ฝึกล่าสุด",
    "Confidence": "ความเชื่อมั่น",
    "No data": "ไม่มีข้อมูล",
    "Add complete exercise details": "เพิ่มรายละเอียดท่าครบถ้วน",
    "Add strength details": "เพิ่มรายละเอียดการฝึกเวท",
    "Add exercises and sets, or save a quick muscle and intensity summary.": "เพิ่มท่าและเซต หรือบันทึกสรุปกล้ามเนื้อและความหนักแบบรวดเร็ว",
    "No templates yet": "ยังไม่มีเทมเพลต",
    "Not set": "ยังไม่กำหนด",
    "Template name": "ชื่อเทมเพลต",
    "Create custom exercise": "สร้างท่ากำหนดเอง",
    "Search exercises or aliases": "ค้นหาชื่อท่าหรือชื่อเรียกอื่น",
    "Workout templates": "เทมเพลตการฝึก",
    "Create from current workout": "สร้างจากการฝึกครั้งนี้",
    "Set type": "ประเภทเซต",
    "Warm-up": "วอร์มอัป",
    "Working": "เซตหลัก",
    "Drop": "ดรอปเซต",
    "Failure": "จนหมดแรง",
    "Stop": "หยุด",
    "Save": "บันทึก",
    "Saving…": "กำลังบันทึก…",
    "Cancel": "ยกเลิก",
    "Done": "เสร็จสิ้น",
    "Delete": "ลบ",
    "Remove": "นำออก",
    "Hard": "หนัก",
    "Full Body": "ทั่วร่างกาย",
    "Upper Body": "ร่างกายส่วนบน",
    "Lower Body": "ร่างกายส่วนล่าง",
    "Core": "แกนกลางลำตัว",
    "%lld exercises": "%lld ท่า",
    "Confidence: %@": "ความเชื่อมั่น: %@",
    "Estimated Muscular Load %lld out of 100": "ภาระกล้ามเนื้อโดยประมาณ %lld จาก 100",
    "Estimated Muscular Load: %lld/100 · Confidence: %@": "ภาระกล้ามเนื้อโดยประมาณ: %lld/100 · ความเชื่อมั่น: %@",
    "Exercise actions for %@": "ตัวเลือกสำหรับท่า %@",
    "Favorite %@": "ตั้ง %@ เป็นท่าโปรด",
    "%@, %@ estimated load": "%@ ภาระโดยประมาณระดับ%@",
    "Rest": "พัก",
    "Muscular": "กล้ามเนื้อ",
    "Total": "รวม",
    "Sets": "เซต",
    "Volume": "ปริมาณรวม",
    "Aliases separated by commas": "ชื่อเรียกอื่น คั่นด้วยจุลภาค",
    "BACK": "ด้านหลัง",
    "Bodyweight exercise": "ท่าที่ใช้น้ำหนักตัว",
    "Both": "ทั้งสองข้าง",
    "Equipment": "อุปกรณ์",
    "Equipment and load": "อุปกรณ์และแรงต้าน",
    "Exercise identity": "ข้อมูลท่า",
    "Exercise name": "ชื่อท่า",
    "Exercise name is required.": "กรุณาระบุชื่อท่า",
    "FRONT": "ด้านหน้า",
    "Left": "ซ้าย",
    "Movement pattern": "รูปแบบการเคลื่อนไหว",
    "Muscles": "กล้ามเนื้อ",
    "None": "ไม่มี",
    "Not to failure": "ไม่ได้ทำจนหมดแรง",
    "Primary muscle": "กล้ามเนื้อหลัก",
    "Reached failure": "ทำจนหมดแรง",
    "Right": "ขวา",
    "Secondary muscle": "กล้ามเนื้อรอง",
    "Side": "ข้าง",
    "Unilateral exercise": "ท่าฝึกข้างเดียว",
    "SET": "เซต",
    "REPS": "ครั้ง",
    "RPE": "RPE",
    "RIR": "RIR",
    "Bodyweight": "น้ำหนักตัว",
    "Estimated 1RM: %.1f kg": "1RM โดยประมาณ: %.1f kg",
    "History": "ประวัติ",
    "No previous sessions": "ยังไม่มีการฝึกครั้งก่อน",
    "Personal best": "สถิติส่วนตัว",
    "Everything on this screen stays in this app. It is included in Coach context only when “Let the coach use my data” is on.": "ข้อมูลทั้งหมดในหน้านี้จะอยู่ภายในแอป และจะรวมในบริบทของโค้ชเมื่อเปิด “อนุญาตให้โค้ชใช้ข้อมูลของฉัน” เท่านั้น",
    "Coach profile": "โปรไฟล์โค้ช",
    "LOCAL COACH PROFILE": "โปรไฟล์โค้ชในอุปกรณ์",
    "Primary goals": "เป้าหมายหลัก",
    "Strength, endurance, sleep": "เวท ความอึด การนอน",
    "Sports and activities": "กีฬาและกิจกรรม",
    "Football, running, lifting": "ฟุตบอล วิ่ง เวท",
    "Experience": "ประสบการณ์",
    "Beginner": "เริ่มต้น",
    "Intermediate": "ปานกลาง",
    "Preferred training days": "วันที่สะดวกฝึก",
    "Monday, Wednesday, Saturday": "จันทร์ พุธ เสาร์",
    "Available time": "เวลาที่มี",
    "%lld min": "%lld นาที",
    "Available equipment": "อุปกรณ์ที่มี",
    "Barbell, dumbbells, bodyweight": "บาร์เบล ดัมเบล น้ำหนักตัว",
    "Current training limitations": "ข้อจำกัดในการฝึกตอนนี้",
    "Preferred coaching language": "ภาษาที่ต้องการให้โค้ชใช้",
    "Thai": "ภาษาไทย",
    "OPTIONAL CHECK-IN": "เช็กอิน (ไม่บังคับ)",
    "Soreness can modestly adjust estimated residual load.": "ความล้ากล้ามเนื้ออาจปรับค่าภาระคงค้างโดยประมาณเล็กน้อย",
    "Overall soreness": "ความล้ากล้ามเนื้อโดยรวม",
    "Muscle": "กล้ามเนื้อ",
    "Soreness": "ระดับความล้า",
    "%lld/10": "%lld/10",
    "How you feel": "อาการที่รู้สึก",
    "Pain or discomfort": "อาการเจ็บหรือไม่สบาย",
    "Not reported": "ไม่ได้ระบุ",
    "Pain/discomfort note": "รายละเอียดอาการเจ็บหรือไม่สบาย",
    "Coach will not diagnose this": "โค้ชจะไม่วินิจฉัยอาการนี้",
    "Delete check-in": "ลบเช็กอิน",
    "New default instructions": "คำแนะนำเริ่มต้นชุดใหม่",
    "Keep custom": "ใช้คำสั่งที่กำหนดเองต่อ",
    "Use new default": "ใช้ค่าเริ่มต้นใหม่",
    "Coach profile & check-in": "โปรไฟล์โค้ชและเช็กอิน",
    "Add local goals, schedule, equipment and an optional soreness check-in.": "เพิ่มเป้าหมาย ตาราง อุปกรณ์ และเช็กอินความล้ากล้ามเนื้อแบบไม่บังคับ",
    "Profile saved locally · check-in available": "บันทึกโปรไฟล์ในอุปกรณ์แล้ว · มีข้อมูลเช็กอิน",
    "New default coach instructions": "คำแนะนำเริ่มต้นใหม่สำหรับโค้ช",
    "Your custom instructions are untouched. Review the safer, freshness-aware default.": "คำสั่งที่คุณกำหนดเองยังคงเดิม ตรวจสอบค่าเริ่มต้นใหม่ที่คำนึงถึงความสดของข้อมูลและความปลอดภัยมากขึ้น",
    "Duration: %lld min": "ระยะเวลา: %lld นาที",
    "Could not save strength details": "บันทึกรายละเอียดการฝึกเวทไม่สำเร็จ",
    "Could not save strength workout": "บันทึกการฝึกเวทไม่สำเร็จ",
}


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def main() -> None:
    document = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = document["strings"]
    for english, thai in THAI.items():
        entry = strings.setdefault(english, {})
        localizations = entry.setdefault("localizations", {})
        english_value = ENGLISH.get(english, english)
        localizations.setdefault("en", unit(english_value))
        # Keep the project's strict all-locale CI gate green. These locales
        # intentionally use the English source until their maintainers provide
        # reviewed translations; Thai remains the complete localized target.
        for locale in FALLBACK_LOCALES:
            localizations.setdefault(locale, unit(english_value))
        localizations["th"] = unit(thai)
    CATALOG.write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {len(THAI)} English/Thai strength strings in {CATALOG}")


if __name__ == "__main__":
    main()
